### ISSUE TITLE
[FEATURE]: Better error messages for missing data

### ISSUE THREAD

**Issue by WardLT** [gpauloski/ProxyStore#29]
### Describe the Request

ProxyStore returns "None" when you attempt to access data with a key that doesn't exist in the database. Having ProxyStore through an Exception or at least print a warning to log would avoid some weird error messages resulting from variables being given a None value.

**Comment by WardLT** [comment]
PS. Your "Feature Form" template is beautiful.

**Comment by gpauloski** [comment]
I see two different questions here and I have different opinions on both of them: should `Store.get()` raise an exception on a missing key and should a proxy raise an exception if its target object is missing in the backend store.

For the first question, I typically use exceptions when something happens that should not given proper use of the library.

For a key-value store, it is reasonable to have missing keys as a part of proper use (because keys can be evicted). E.g., for a distributed cache, cache misses are expected. (Here's where I need to acknowledge that dicts do raise `KeyError` and a key-value store is functionally similar to a dict. Since dicts are local to a processes, that process controls all access to the dict whereas ProxyStore backends can be accessed by many independent processes.)

Users may not handle `None` return values, though, and that could cause unexpected results. My hope is that the signature `get(key: str, default: Any | None = None) -> Any | None` strongly hints to handle the default/not found case if necessary.

Raising exceptions seems like a higher burden to me. When missing keys are okay, every `get()` operation needs to by wrapped with a `try/except`. When missing keys are bad, many `get()` operations still need to be wrapped with `try/except` to control how much exception bubbles up in the function stack or do some cleanup before exiting. Also, `get()` will raise exceptions from the underlying stores (e.g., not being able to connect to Redis or a filesystem error), so users also need to be careful not to write bare excepts.

I guess the TL;DR is missing keys in key-value stores is common so `get()` raising an exception requires a lot of `try/except`s when `if get(key) is None` is (arguably) more flexible.

For the second question though, since a proxy represents a real object created by the program, failing to resolve to the target object _is_ unexpected behavior given proper use of ProxyStore. For this, I will add a `ProxyFactoryResolveError` type and raise that when the target is not found in the backend store.

...bit of a verbose response but I had to contemplate the philosophy of Python semantics!
